### ISSUE TITLE
全屏存在问题

### ISSUE THREAD

**Issue by tonight-love** [sonichy/HTYMediaPlayer_QtAV#1]
![image](https://user-images.githubusercontent.com/16730960/39111529-0a397e00-4708-11e8-92e7-948f8ae47c11.png)
问题1. 全屏下，移动鼠标 功能显示模块闪烁。
问题2. 全屏拖回到小屏模式 显示错乱。
 Windows 环境

**Comment by sonichy** [comment]
问题1：移动鼠标，显示控制栏，一段时间后隐藏，快速移动鼠标触发多次显示隐藏，即为闪烁，由于无法中止上次的事件，暂时没有好的办法解决。
问题2：可能是视频分辨率为 0 x 0 引起的，Ctrl + i 看看分辨率是不是 0 x 0，马上修这个Bug。

**Comment by tonight-love** [comment]
不好意思 我是一个Java开发 首次看qt 相关的东西 ，以下是我站着我的角度的一些处理方式 ，不知道有没有问题。
问题1：全屏模式下，首次移动鼠标 开始显示状态栏   状态栏显示后  设置 一个状态栏显示的状态 和 状态栏显示的剩余时长（如3秒钟）。相当于3秒钟之后 隐藏状态栏。后面鼠标移动，首先要判断当前状态栏的状态  如果当前状态未显示  则显示状态栏 设置参数  如果当前状态栏显示  则设置剩余时长为3 秒
问题2.我是在没有播放视频的状态下点击全屏 然后又点了一下 就成这样了 。

**Comment by sonichy** [comment]
问题1：已经按你的想法改好了：
if (CP->isHidden()) {
            CP->show();
            setCursor(QCursor(Qt::ArrowCursor));
            QTimer::singleShot(5000,this,SLOT(hideCP()));
}
问题2：今天上午已经改好。
开不开心？

**Comment by tonight-love** [comment]
O(∩_∩)O哈哈~☺，好开心，我去试试 。

**Comment by tonight-love** [comment]
说真的，想不到你会按照我的想法来修改代码，哈哈

**Comment by sonichy** [comment]
受了JS的影响，只想到通过timer事件的id去clear，但是QTimer没有id，clear不了。
但是从另外一个角度，从控件显隐状态可以决定是否触发事件，问题解决了。

**Comment by tonight-love** [comment]
厉害了我的哥，棒棒哒
